In [27]:
import pandas as pd

df_43 = pd.read_csv('/home/gui/hf_dev/datatrove/blogpost/data/top_60k_urls_CC_MAIN_2021_43.csv').sort_values(by="Frequency", ascending=False)
df_49 = pd.read_csv('/home/gui/hf_dev/datatrove/blogpost/data/top_60k_urls_CC_MAIN_2021_49.csv').sort_values(by="Frequency", ascending=False)

In [28]:
freqs_49 = {row[1]["URL"]: row[1]["Frequency"] for row in df_49.iterrows()}

In [29]:
df_43['in_49'] = df_43.apply(lambda row: freqs_49.get(row["URL"], 0), axis=1)
df_43['change_to_49'] = df_43.apply(lambda row: freqs_49.get(row["URL"], 0) - row["Frequency"], axis=1)

In [30]:
df_43

                           URL  Frequency     in_49  change_to_49
0         worldwidescience.org   0.001337  0.001317 -2.004393e-05
1                    issuu.com   0.001006  0.000992 -1.395550e-05
2             en.wikipedia.org   0.000824  0.001125  3.004770e-04
3          caselaw.findlaw.com   0.000661  0.000228 -4.330254e-04
4          www.frontiersin.org   0.000611  0.000402 -2.088168e-04
...                        ...        ...       ...           ...
59995  www.basketballghana.com   0.000001  0.000002  7.485694e-07
59996           meisendorf.com   0.000001  0.000000 -1.323341e-06
59997     www.anyrubbish.co.uk   0.000001  0.000000 -1.323290e-06
59998               qjshhxx.cn   0.000001  0.000000 -1.323239e-06
59999    www.al-enterprise.com   0.000001  0.000000 -1.323225e-06

[60000 rows x 4 columns]

In [16]:
freqs_49

{'worldwidescience.org': 0.0013371601446593,
 'issuu.com': 0.0010055409292792,
 'en.wikipedia.org': 0.0008242551989742,
 'caselaw.findlaw.com': 0.0006608764065299,
 'www.frontiersin.org': 0.0006109349846815,
 'chroniclingamerica.loc.gov': 0.0005375644622649,
 'www.nature.com': 0.0005266164399221,
 'lookformedical.com': 0.0004704824927555,
 'en.m.wikipedia.org': 0.0004443793906608,
 'ufdc.ufl.edu': 0.0004426934126914,
 'journals.plos.org': 0.0004371460070378,
 'casetext.com': 0.0003903933122818,
 'hansard.parliament.uk': 0.0003611472676514,
 'search.audioburst.com': 0.0003535316041847,
 'ivy.fm': 0.0003530053155805,
 'link.springer.com': 0.0003286474058102,
 'www.newageislam.com': 0.0003196897846979,
 'www.studylight.org': 0.0003159274076666,
 'panewsarchive.psu.edu': 0.0003121250457216,
 'www.theguardian.com': 0.0003038877330206,
 'bmcgenomics.biomedcentral.com': 0.0002553320996198,
 'law.justia.com': 0.0002463165002013,
 'www.hotfreebooks.com': 0.0002438439057772,
 'www.hindawi.com': 0.0002374853040569,
 'zims-en.kiwix.campusafrica.gos.orange.com': 0.0002318541153106,
 'discover.hubpages.com': 0.0002314644626707,
 'www.fanfiction.net': 0.00023022444825,
 'www.huffpost.com': 0.0002272851203057,
 'nebnewspapers.unl.edu': 0.0002254127055625,
 'www.angi.com': 0.0002231034435845,
 'www.theyworkforyou.com': 0.0002208272250724,
 'www.ola.org': 0.000218709862407,
 'www.wikihow.com': 0.0002180965139118,
 'acp.copernicus.org': 0.0002111536489058,
 'www.semanticscholar.org': 0.0001950019041289,
 'www.theatlantic.com': 0.0001913746442804,
 'docplayer.net': 0.0001907412725177,
 'irclogs.ubuntu.com': 0.0001898102449522,
 'www.forbes.com': 0.00018939073865,
 'publications.waset.org': 0.0001873821881616,
 'www.washingtonpost.com': 0.0001866054782221,
 'subsaga.com': 0.0001865089939112,
 'www.nybooks.com': 0.000184557446664,
 'newspapers.library.wales': 0.0001845348751784,
 'www.dailymail.co.uk': 0.0001837949675985,
 'deepai.org': 0.0001831206612305,
 'www.gastearsivi.com': 0.0001817473130172,
 'transparentpng.netlify.app': 0.0001812971084796,
 'api.parliament.uk': 0.0001797907418292,
 'pubmed.ncbi.nlm.nih.gov': 0.0001747089206415,
 'gateway.ipfs.io': 0.0001725078365045,
 'www.thefreelibrary.com': 0.0001708132388158,
 'alumnius.net': 0.0001683239812924,
 'www.yumpu.com': 0.0001673814233117,
 'www.inkitt.com': 0.0001636112276366,
 'm.fanfiction.net': 0.0001552928359265,
 'contracts.justia.com': 0.0001548855632462,
 'patents.google.com': 0.0001517315288932,
 'www.latimes.com': 0.0001510611082861,
 'www.arxiv-vanity.com': 0.0001493404557011,
 'bmcpublichealth.biomedcentral.com': 0.0001492791353507,
 'www.telegraph.co.uk': 0.0001486748451729,
 'archiveofourown.org': 0.0001479185499767,
 'www.economist.com': 0.0001453357732099,
 'studylib.net': 0.0001453062312784,
 'www.espn.com': 0.0001440956536707,
 'hubpages.com': 0.0001390828482346,
 'time.com': 0.000137760710869,
 'www.ipl.org': 0.0001376025183566,
 'robineko.com': 0.0001360150473236,
 'www.advocatekhoj.com': 0.0001359044227581,
 'www.tumgir.com': 0.000135691851343,
 'www.counterpunch.org': 0.0001340337950299,
 'tropedia.fandom.com': 0.000133800765374,
 'www.encyclopedia.com': 0.00013326334508,
 'www.nbcnews.com': 0.0001321288877867,
 'veranstaltungen.badminton.de': 0.0001317963108835,
 'slate.com': 0.0001308241783483,
 'patents.justia.com': 0.0001259783845068,
 'www.british-history.ac.uk': 0.0001259638274029,
 'bmchealthservres.biomedcentral.com': 0.0001243383360853,
 'dokumen.pub': 0.0001212929181714,
 'alchetron.com': 0.0001211202772984,
 'scocal.stanford.edu': 0.000121076402999,
 'www.avclub.com': 0.0001200605774033,
 'www.preceptaustin.org': 0.0001200404127696,
 'www.politico.com': 0.0001198441927229,
 'voracity.e-fic.com': 0.0001192375681888,
 'bmcbioinformatics.biomedcentral.com': 0.0001189960674294,
 'www.smh.com.au': 0.0001184023181027,
 'datatracker.ietf.org': 0.0001181400473718,
 'www.seattletimes.com': 0.0001175724181873,
 'm.scirp.org': 0.0001172250594441,
 'www.independent.co.uk': 0.0001172085630845,
 'www.theglobeandmail.com': 0.0001169944801374,
 'blogs.sap.com': 0.0001168635749453,
 'www.airtasker.com': 0.0001165835971794,
 'bmccancer.biomedcentral.com': 0.0001165253723884,
 'newrepublic.com': 0.0001156806326365,
 'en.wikisource.org': 0.0001146742133368,
 'www.newworldencyclopedia.org': 0.0001145322380761,
 'docs.justia.com': 0.0001144089739136,
 'www.fool.com': 0.0001144039245994,
 'www.vox.com': 0.0001139990805197,
 'moz.com': 0.0001138081019004,
 'www.fastcompany.com': 0.0001133714141558,
 'www.thedailybeast.com': 0.0001121551963952,
 'grantland.com': 0.0001121058124351,
 'apps.apple.com': 0.0001097454882252,
 'www.cdc.gov': 0.0001070063277096,
 'techcrunch.com': 0.0001061237416623,
 'www.bostonglobe.com': 0.0001050931342265,
 'www.creativelive.com': 0.0001047344988024,
 'www.si.com': 0.0001044359259311,
 'devrant.com': 0.0001040909704149,
 'www.opendemocracy.net': 0.0001039552116465,
 'gizmodo.com': 0.0001036007519653,
 'www.healthline.com': 0.0001035295830961,
 'thehockeywriters.com': 0.0001025606947362,
 'www.npr.org': 0.0001020513809621,
 'www.jpost.com': 0.0001018387189275,
 'www.newstatesman.com': 0.0001016472835864,
 'bleacherreport.com': 0.0001013723877576,
 'www.foxnews.com': 0.000101312256334,
 'www.apotelyt.com': 0.0001010690519295,
 'archive.org': 9.968097987253116e-05,
 'www.nzherald.co.nz': 9.956585333416228e-05,
 'truthout.org': 9.943359610027588e-05,
 'www.fictionpress.com': 9.892011745752971e-05,
 'www.politico.eu': 9.790526692680434e-05,
 'www.techradar.com': 9.74725918101852e-05,
 'www.prnewswire.com': 9.738541230153274e-05,
 'www.newyorker.com': 9.735472131572091e-05,
 'www.inquirer.com': 9.707689666725828e-05,
 'www.haaretz.com': 9.671520555620812e-05,
 'digital.bentley.umich.edu': 9.671287844945354e-05,
 'thepointsguy.com': 9.628801110222596e-05,
 'www.thoughtco.com': 9.607799153001185e-05,
 'www.openpr.com': 9.553215812886762e-05,
 'encyclopedia2.thefreedictionary.com': 9.500022574704412e-05,
 'www.usatoday.com': 9.488317082737702e-05,
 'www.democracynow.org': 9.415912889588526e-05,
 'www.cnn.com': 9.4023819599869e-05,
 'www.abc.net.au': 9.389910915143912e-05,
 'www.chicagotribune.com': 9.352145452302566e-05,
 'dictionnaire.sensagent.leparisien.fr': 9.26353234439554e-05,
 'bioresources.cnr.ncsu.edu': 9.263514582988844e-05,
 'contract4j.org': 9.26177287769977e-05,
 'www.motortrend.com': 9.25636108582342e-05,
 'www.canada.ca': 9.242836680820172e-05,
 'www.salon.com': 9.222098969833042e-05,
 'www.thestar.com': 9.19553624240566e-05,
 'www.reuters.com': 9.194116054825516e-05,
 'publications.parliament.uk': 9.19099077220275e-05,
 'tvtropes.org': 9.137703652299302e-05,
 'www.instructables.com': 9.10100169899347e-05,
 'www.stitcher.com': 9.093581418249948e-05,
 'edition.cnn.com': 9.04522725719749e-05,
 'www.inc.com': 9.042346647013876e-05,
 'mickopedia.org': 9.03179963373684e-05,
 'www.rollingstone.com': 8.991108613478614e-05,
 'oregonnews.uoregon.edu': 8.958794815059258e-05,
 'military.wikia.org': 8.950105499931337e-05,
 'supersearch.can.ucsd.edu': 8.913234632023067e-05,
 'www.rt.com': 8.907333857746101e-05,
 'dilbert.com': 8.872705639291213e-05,
 'www.instantcheckmate.com': 8.847558024756348e-05,
 'scienceblogs.com': 8.833675854275406e-05,
 'www.nap.edu': 8.760726132206345e-05,
 'venturebeat.com': 8.734926420311428e-05,
 'www.lastminute.com': 8.725486413892421e-05,
 'www.thesun.co.uk': 8.722505759867021e-05,
 'www.buzzfeednews.com': 8.717305654960247e-05,
 'ilgotha.org': 8.713850880119424e-05,
 'www.finder.com': 8.69887910170946e-05,
 'laagvlieger.x24hr.com': 8.674987109884553e-05,
 'www.cheatsheet.com': 8.580867603424703e-05,
 '75-3-247-200.lightspeed.sntcca.sbcglobal.net': 8.560513031353399e-05,
 'themillions.com': 8.537252838138035e-05,
 'www.mic.com': 8.527057065740314e-05,
 'www.baltimoresun.com': 8.519745165825395e-05,
 'www.lrb.co.uk': 8.511623128278618e-05,
 'suptg.thisisnotatrueending.com': 8.504496091984392e-05,
 'www.eurasiareview.com': 8.477297578692904e-05,
 'www.news.com.au': 8.465024084189674e-05,
 'www.firstpost.com': 8.437763224735913e-05,
 'journals.lww.com': 8.429768416857495e-05,
 'insecure.archiveofourown.org': 8.37850319749566e-05,
 'www.bristolpost.co.uk': 8.359137464556217e-05,
 'www.vice.com': 8.343498364723322e-05,
 'kanithamizh.in': 8.289961860170783e-05,
 '33.agilestudio.cn': 8.202731242164385e-05,
 'www.colombotelegraph.com': 8.186559662608357e-05,
 'www.icty.org': 8.181046739457158e-05,
 'www.pcmag.com': 8.167827903144583e-05,
 'www.globalsecurity.org': 8.133342138420935e-05,
 'transcripts.cnn.com': 8.113191641287768e-05,
 'www.indiewire.com': 8.110638710933774e-05,
 'www.denofgeek.com': 8.093316264719514e-05,
 'www.smithsonianmag.com': 8.085372203717366e-05,
 'www.bailii.org': 8.072180553231362e-05,
 'www.thisismoney.co.uk': 8.06264956491276e-05,
 'www.bartleby.com': 8.037844491792707e-05,
 'www.express.co.uk': 8.037329773476269e-05,
 'www.csmonitor.com': 8.036398930774429e-05,
 'www.irishexaminer.com': 8.036148096214588e-05,
 'yaledailynews.com': 8.031070146288547e-05,
 'www.texasmonthly.com': 8.021909610166704e-05,
 'fr.slideserve.com': 8.019415401198106e-05,
 'www.speakingtree.in': 8.013157586398822e-05,
 'en.m.wikiquote.org': 7.987411883679364e-05,
 'heavy.com': 7.941452975186778e-05,
 'www.mentalfloss.com': 7.925765303343739e-05,
 'www.romper.com': 7.902143719873806e-05,
 'nypost.com': 7.891734810595757e-05,
 'de.zxc.wiki': 7.869296354298256e-05,
 'www.tripsavvy.com': 7.866977222052784e-05,
 'www.inverse.com': 7.846257634950035e-05,
 'www.ukessays.com': 7.822928208496332e-05,
 'erhverv.studentersamfundet.aau.dk': 7.788662830206765e-05,
 'www.ajmc.com': 7.778079931638652e-05,
 'www.cnet.com': 7.776564049948973e-05,
 'www.aljazeera.com': 7.776164962014891e-05,
 'www.theverge.com': 7.771762670498596e-05,
 'www.kayak.com': 7.758318373064315e-05,
 'homeguides.sfgate.com': 7.750585999031743e-05,
 'medium.com': 7.744013553599594e-05,
 'philarchive.org': 7.742044574800376e-05,
 'wikimili.com': 7.71816454473916e-05,
 'www.hollywoodreporter.com': 7.709207721077766e-05,
 'www.boloji.com': 7.692111098462902e-05,
 'www.readkong.com': 7.682233943952609e-05,
 'parasitesandvectors.biomedcentral.com': 7.654496788817299e-05,
 'shakespir.com': 7.649789653565706e-05,
 'docoh.com': 7.647789501685351e-05,
 'www.thestreet.com': 7.587663152771657e-05,
 'www.quotemaster.org': 7.578018346459137e-05,
 'pizza.dominos.com': 7.554430473414153e-05,
 'www.crikey.com.au': 7.552816722748815e-05,
 'ew.com': 7.54755717150127e-05,
 'aspe.hhs.gov': 7.542470159633038e-05,
 'en.wikibooks.org': 7.538765637665437e-05,
 'www.deseret.com': 7.517427301149898e-05,
 'www.huffingtonpost.co.uk': 7.506976706937772e-05,
 'thehill.com': 7.506696149207544e-05,
 'www.businesswire.com': 7.447800774521049e-05,
 'finance.yahoo.com': 7.432127601785517e-05,
 'www.patheos.com': 7.431243156227694e-05,
 'gahistoricnewspapers.galileo.usg.edu': 7.409300569406873e-05,
 'www.thisdaylive.com': 7.401369920079166e-05,
 'www.hindustantimes.com': 7.400497073807348e-05,
 'americanliterature.com': 7.39991203481951e-05,
 'www.govinfo.gov': 7.398683597936124e-05,
 'www.vulture.com': 7.397641837061869e-05,
 'www.verywellhealth.com': 7.367888943505635e-05,
 'edwardbetts.com': 7.347130933767997e-05,
 'www.osapublishing.org': 7.340340639245581e-05,
 'jamanetwork.com': 7.339769374409872e-05,
 'worldcrunch.com': 7.332037362854988e-05,
 'journals.biologists.com': 7.314969738455134e-05,
 'www.knowpia.com': 7.278462073189873e-05,
 'www.japantimes.co.jp': 7.270068177377371e-05,
 'casestudylion.com': 7.267251725744468e-05,
 'listverse.com': 7.263129629480715e-05,
 'www.wired.com': 7.262107079923904e-05,
 'reason.com': 7.227048600453796e-05,
 'www.pcworld.com': 7.210347803473826e-05,
 'lrb.co.uk': 7.202621229084256e-05,
 'apnews.com': 7.177186894698473e-05,
 'vault.si.com': 7.175390092800879e-05,
 'www.mirror.co.uk': 7.167631257897111e-05,
 'www.washingtontimes.com': 7.157697919345235e-05,
 'abcnews.go.com': 7.154017320905017e-05,
 'www.michigandaily.com': 7.145109069253766e-05,
 'japantoday.com': 7.141615509300366e-05,
 'www.indystar.com': 7.137189294256688e-05,
 'www.alternet.org': 7.133872260937165e-05,
 'brooklynrail.org': 7.131313530940169e-05,
 'www.angelfire.com': 7.12078065429295e-05,
 'www.cracked.com': 7.115592873627557e-05,
 'www.nj.com': 7.110599381002733e-05,
 'washingtoncitypaper.com': 7.102516853523909e-05,
 'www.lifehack.org': 7.096077437403122e-05,
 'www.cbc.ca': 7.093102945498411e-05,
 'www.etsy.com': 7.086754148799531e-05,
 'www.wnd.com': 7.084338235011462e-05,
 'thenextweb.com': 7.078859022285212e-05,
 'www.paperdue.com': 7.078620874444437e-05,
 'www.intechopen.com': 7.062377161828572e-05,
 'core-cms.prod.aop.cambridge.org': 7.005774096038663e-05,
 'www.foxbusiness.com': 6.999398113513212e-05,
 'www.freep.com': 6.994770723352898e-05,
 'www.rxlist.com': 6.978336709951025e-05,
 'variety.com': 6.975902309800886e-05,
 'news.yahoo.com': 6.969056918669951e-05,
 'thoughtcatalog.com': 6.942696816269956e-05,
 'www.afr.com': 6.928289415619634e-05,
 'www.frontstretch.com': 6.924485212287934e-05,
 'www.yahoo.com': 6.923795054770682e-05,
 'counter-currents.com': 6.914461254314151e-05,
 'www.macworld.com': 6.895888622555247e-05,
 'www.actionnetwork.com': 6.890092604330007e-05,
 'www.thenation.com': 6.889150162342162e-05,
 'supreme.justia.com': 6.858906111519188e-05,
 'www.technologyreview.com': 6.842741419039226e-05,
 'www.bbc.com': 6.82069081386749e-05,
 'www.answers.com': 6.810150325188831e-05,
 'www.tomsguide.com': 6.802705033484864e-05,
 'qz.com': 6.796972086377271e-05,
 'locations.acima.com': 6.781505888401377e-05,
 'www.pajiba.com': 6.774461134542243e-05,
 'www.slideserve.com': 6.767139447729758e-05,
 'www.cinemablend.com': 6.707308880609173e-05,
 'www.scoop.co.nz': 6.700737160132399e-05,
 'www.desmoinesregister.com': 6.696830375615098e-05,
 'nationalpost.com': 6.695414175289518e-05,
 'www.edweek.org': 6.689663466775233e-05,
 'www.yukon-news.com': 6.681017648969827e-05,
 'bmcinfectdis.biomedcentral.com': 6.676929263131023e-05,
 'hbr.org': 6.664135975623728e-05,
 'www.zdnet.com': 6.661904562978665e-05,
 'www.lifesitenews.com': 6.656624712980612e-05,
 'www.lifenews.com': 6.648742635663048e-05,
 'projects.sare.org': 6.648619393249253e-05,
 'www.aanda.org': 6.623126337478073e-05,
 'www.thenationalnews.com': 6.621839179209292e-05,
 'www.digitaltrends.com': 6.600602698923979e-05,
 'dzone.com': 6.590109332344712e-05,
 'cc.bingj.com': 6.589474996391355e-05,
 'www.cnbc.com': 6.588816736910614e-05,
 'www.today.com': 6.586893792777725e-05,
 'www.tor.com': 6.58186260247339e-05,
 'www.scotsman.com': 6.567917723352487e-05,
 'incidecoder.com': 6.564429238086714e-05,
 'nymag.com': 6.561455833615067e-05,
 'www.pbs.org': 6.54957526492523e-05,
 'www.entrepreneur.com': 6.546032408006312e-05,
 'www.aol.com': 6.534515766914859e-05,
 'deadline.com': 6.521372688439e-05,
 'www.azcentral.com': 6.515080438259391e-05,
 'chicagoreader.com': 6.509821611967221e-05,
 'www.plymouthherald.co.uk': 6.485229313249809e-05,
 'www.inman.com': 6.484517044593611e-05,
 'www.rediff.com': 6.465703727650121e-05,
 'github.com': 6.455723629476541e-05,
 'www.theepochtimes.com': 6.435335346980286e-05,
 'indianexpress.com': 6.421343345759994e-05,
 'smallbusiness.chron.com': 6.420471949398925e-05,
 'todayinsci.com': 6.418823400875574e-05,
 'www.biblegateway.com': 6.416743866381627e-05,
 'www.computerweekly.com': 6.40963241662797e-05,
 'electricscotland.com': 6.40196528857917e-05,
 'www.eurekalert.org': 6.398032768146048e-05,
 'chestofbooks.com': 6.388934940664165e-05,
 'wwd.com': 6.380502622216775e-05,
 'www.vanityfair.com': 6.37191190101989e-05,
 'www.detroitnews.com': 6.369564133037095e-05,
 'www.popsci.com': 6.354896110929367e-05,
 'email.varsitytutors.com': 6.349104442436378e-05,
 'unispal.un.org': 6.334205522041628e-05,
 'www.stylist.co.uk': 6.33394961279416e-05,
 'www.polygon.com': 6.3172749142077e-05,
 'spectator.org': 6.305600595322126e-05,
 'www.trustedreviews.com': 6.28778300458656e-05,
 'matadornetwork.com': 6.286947493516568e-05,
 'www.bizpacreview.com': 6.274636663811513e-05,
 'cloudflare-ipfs.com': 6.264667439968561e-05,
 'moderndiplomacy.eu': 6.260917608290006e-05,
 'www.cyclingnews.com': 6.254338275781793e-05,
 'www.orlandosentinel.com': 6.235571718460006e-05,
 'torontosun.com': 6.229324415513663e-05,
 'hindi.hwnews.in': 6.223899936918246e-05,
 'www.nakedcapitalism.com': 6.218519318123032e-05,
 'www.golfdigest.com': 6.213693290189896e-05,
 'www.indiatoday.in': 6.208597578857161e-05,
 'admin.rushlimbaugh.com': 6.205893857785112e-05,
 'slideplayer.com': 6.194997416017198e-05,
 'koreajoongangdaily.joins.com': 6.189866544348762e-05,
 'www.discovermagazine.com': 6.185195294388246e-05,
 'www.ncronline.org': 6.178336491582866e-05,
 'scroll.in': 6.174224182216679e-05,
 'www.elephantjournal.com': 6.153964579299534e-05,
 'www.eadt.co.uk': 6.147534950076313e-05,
 'www.mlb.com': 6.127388802675397e-05,
 'signalscv.com': 6.126671096853886e-05,
 'www.genomeweb.com': 6.11374333012448e-05,
 'sabr.org': 6.11251996792872e-05,
 'www.liverpoolecho.co.uk': 6.105908374906308e-05,
 'www.tomshardware.com': 6.105648115926588e-05,
 'blogs.lse.ac.uk': 6.087712357464855e-05,
 'lawprofessors.typepad.com': 6.073721806155311e-05,
 'www.walesonline.co.uk': 6.073342654494048e-05,
 'www.rferl.org': 6.072680770236432e-05,
 'www.treatwell.co.uk': 6.070949214322612e-05,
 'www.straitstimes.com': 6.070556650986906e-05,
 'wccftech.com': 6.061624113330584e-05,
 'genomebiology.biomedcentral.com': 6.0551513492625336e-05,
 'www.refinery29.com': 6.031577612847368e-05,
 'profiles.stanford.edu': 6.031038246048171e-05,
 'www.rollcall.com': 6.0308276465116567e-05,
 'wol.jw.org': 6.020821812422255e-05,
 'translational-medicine.biomedcentral.com': 6.0120034552375366e-05,
 'www.sun-sentinel.com': 6.006348803310472e-05,
 'www.varsitytutors.com': 6.002798696837802e-05,
 'salesandmarketingnetwork.com': 5.997694286040564e-05,
 'www.nottinghampost.com': 5.986280951090086e-05,
 'www.dailypress.com': 5.9842826115981694e-05,
 'thestuffedbakedpotatofactory.com': 5.982481459968324e-05,
 'www.catholicculture.org': 5.978192986445947e-05,
 'www.wsws.org': 5.972766695462091e-05,
 'www.irishcentral.com': 5.962983060195208e-05,
 'db0nus869y26v.cloudfront.net': 5.961873153515678e-05,
 'www.brookings.edu': 5.9409991509179976e-05,
 'www.tripadvisor.com': 5.919981969633702e-05,
 'docs.microsoft.com': 5.914151153550449e-05,
 'www.courant.com': 5.906802280911392e-05,
 'www.gearpatrol.com': 5.8947230744487336e-05,
 'www.thefreedictionary.com': 5.8906499126728096e-05,
 'www.dailyrecord.co.uk': 5.889077121986173e-05,
 'www.hulldailymail.co.uk': 5.880339234848109e-05,
 'www.mycentraljersey.com': 5.868136785971656e-05,
 'www.stokesentinel.co.uk': 5.8600274351439456e-05,
 'bookriot.com': 5.853559020808147e-05,
 'wn.rsarchive.org': 5.845390223639666e-05,
 'chicago.suntimes.com': 5.844645694469269e-05,
 'info.mzalendo.com': 5.843388621848561e-05,
 'www.manchestereveningnews.co.uk': 5.820470970048009e-05,
 'malariajournal.biomedcentral.com': 5.816658792207181e-05,
 'quizlet.com': 5.811156018431234e-05,
 'www.cyclingweekly.com': 5.804181947721189e-05,
 'www.tw.kayak.com': 5.791512627583065e-05,
 'www.opentable.com': 5.791108464961355e-05,
 'www.charityjob.co.uk': 5.780437121837461e-05,
 'thecyberwire.com': 5.769611000740947e-05,
 'bmcresnotes.biomedcentral.com': 5.769451873036076e-05,
 'dev.to': 5.768846172820043e-05,
 'newsblaze.com': 5.767688781563433e-05,
 'mmajunkie.usatoday.com': 5.767364001555314e-05,
 'villains.fandom.com': 5.756588627335069e-05,
 'ar15partspro.com': 5.756451973246832e-05,
 'www.informationweek.com': 5.746075324482982e-05,
 'www.phillymag.com': 5.737931538274948e-05,
 'www.kayak.co.uk': 5.732462837401639e-05,
 'www.mdpi.com': 5.7296170250760384e-05,
 'www.villagevoice.com': 5.728727504830589e-05,
 'www.smore.com': 5.721818680104317e-05,
 'www.outsideonline.com': 5.721286562858873e-05,
 'bgr.com': 5.711787472576781e-05,
 'www.livemint.com': 5.711578685428705e-05,

In [33]:
filtered_df = df_43[df_43['in_49'] == 0]  # Filter rows where 'in_49' is 0
sorted_df = filtered_df.sort_values(by='Frequency', ascending=False)  # Sort by 'Frequency' column in descending order

In [34]:
sorted_df

                              URL  Frequency  in_49  change_to_49
9                    ufdc.ufl.edu   0.000443    0.0     -0.000443
22           www.hotfreebooks.com   0.000244    0.0     -0.000244
37             irclogs.ubuntu.com   0.000190    0.0     -0.000190
47     transparentpng.netlify.app   0.000181    0.0     -0.000181
85          www.preceptaustin.org   0.000120    0.0     -0.000120
...                           ...        ...    ...           ...
59994      www.annahelizabeth.com   0.000001    0.0     -0.000001
59996              meisendorf.com   0.000001    0.0     -0.000001
59997        www.anyrubbish.co.uk   0.000001    0.0     -0.000001
59998                  qjshhxx.cn   0.000001    0.0     -0.000001
59999       www.al-enterprise.com   0.000001    0.0     -0.000001

[29485 rows x 4 columns]

In [36]:
assert all(row[1]["URL"] not in freqs_49 for row in sorted_df.iterrows())